### ISSUE TITLE
Parse dates and times as special string

### ISSUE THREAD

**Issue by CraigBryan** [CraigBryan/tweet-mood-analyzer#3]
Is it a good idea to parse whole dates eg. `February 14th, 2015` or `08/08/08` as `%%DATE%%`?

What about times as `%%TIME%%` from `12:34` or `5pm`?

**Comment by BonShillings** [comment]
I think it's probably fine to just group the whole set under %%date%% or %%time%%, unless we want to extract features out of the times

**Comment by CraigBryan** [comment]
I actually went ahead and did them separately. It actually probably made it easier to do separately, since the regexes could be split up. 

The dates recognize a bunch of formats from 12/12/12 to wed feb 6th, 2015 to 26th of february.
The times recognize things like 12:00, 1pm, 1 PM, 4:00am
