### ISSUE TITLE
Leveraging the sid and uid

### ISSUE THREAD

**Issue by CraigBryan** [CraigBryan/tweet-mood-analyzer#4]
I think it's wise to leave the uid as a feature (maybe we will have more than one tweet by a certain user)? If a user is always negative or positive, Weka may use that.

For the sid, I don't think they have any value on their own, but I believe Twitter tweet id's are actually time stamps? Maybe we could get a date out of that, and have each tweet have a feature of the date it was created. That way, if there is a certain date that had a bunch of bad things happen, Weka would pick up on that.

Let me know what you think.

**Comment by BonShillings** [comment]
I think your probability right about using dates as indications of whether a tweet is negative or not, but im not sure if Weka would be able to pick that up.

**Comment by CraigBryan** [comment]
I was thinking we'd parse the actual date out of the sid, if possible. I'll look into that now.

The uid is now added as a feature. Use -uid to make it active.

**Comment by CraigBryan** [comment]
I couldn't find a sensible date in the sid. I was probably wrong about how twitter id's work, or the sid is possibly not even a twitter id. Who knows.
